### ISSUE TITLE
Why did you get rid of S3 ?

### ISSUE THREAD

**Issue by cadesalaberry** [sahat/cloudbucket#1]
I think the title is self explanatory :-)

**Comment by sahat** [comment]
My AWS was hacked because I put all credentials and keys like an idiot in a repo which is publicly available on github. Someone took advantage and created 15 double extra large instances all over the place, netting me a $1700 AWS bill. 

This project was never a serious product attempt. If anything it gave a tremendous experience with designing and developing mobile web apps.

**Comment by cadesalaberry** [comment]
Wow, not cool, I guess he was mining bitcoins.
Your app looked like a fun project, but It feels a bit too complex to be exploitable.
Good job though, the website looks nice !

**Comment by sahat** [comment]
@cadesalaberry Thanks, there were are a lot of revisions of this web app. At one point I was working on iOS and Android clients. I agree that it is complex. It tries to do too many things at once. Maybe I could come up with some practical applications for it, I could narrow my focus down and pursue that path.
